# Generated by Django 3.2.4 on 2021-07-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zmain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactss',
            old_name='Address',
            new_name='message',
        ),
    ]
