# Generated by Django 3.2.4 on 2021-07-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmain', '0005_blog_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
