# Generated by Django 3.2.4 on 2021-07-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmain', '0009_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('discription', models.TextField(null=True)),
            ],
        ),
    ]
