# Generated by Django 3.2.4 on 2021-06-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactss',
            name='Address',
            field=models.TextField(null=True),
        ),
    ]
